// @flow
export const GET_FORECAST_DAILY:string = 'GET_FORECAST_DAILY'

export const GET_FORECAST_DAILY_PENDING:string = 'GET_FORECAST_DAILY_PENDING'

export const GET_FORECAST_DAILY_FULFILLED:string = 'GET_FORECAST_DAILY_FULFILLED'
