export const GET_FORECAST_DAILY = 'GET_FORECAST_DAILY'

export const GET_FORECAST_DAILY_PENDING = 'GET_FORECAST_DAILY_PENDING'

export const GET_FORECAST_DAILY_FULFILLED = 'GET_FORECAST_DAILY_FULFILLED'
