// @flow
export const GET_FORECAST_HOURLY:string = 'GET_FORECAST_HOURLY'

export const GET_FORECAST_HOURLY_PENDING:string = 'GET_FORECAST_HOURLY_PENDING'

export const GET_FORECAST_HOURLY_FULFILLED:string = 'GET_FORECAST_HOURLY_FULFILLED'

export const SET_FORECAST_HOURLY_ACTIVE_REPORT_TYPE:string = 'SET_FORECAST_HOURLY_ACTIVE_REPORT_TYPE'
