export const GET_LOCATIONS = 'GET_LOCATIONS'

export const GET_LOCATIONS_PENDING = 'GET_LOCATIONS_PENDING'

export const GET_LOCATIONS_FULFILLED = 'GET_LOCATIONS_FULFILLED'

export const SET_SEARCHVALUE = 'SET_SEARCHVALUE'
