export const GET_FORECAST_HOURLY = 'GET_FORECAST_HOURLY'

export const GET_FORECAST_HOURLY_PENDING = 'GET_FORECAST_HOURLY_PENDING'

export const GET_FORECAST_HOURLY_FULFILLED = 'GET_FORECAST_HOURLY_FULFILLED'

export const SET_FORECAST_HOURLY_ACTIVE_REPORT_TYPE = 'SET_FORECAST_HOURLY_ACTIVE_REPORT_TYPE'
